### ISSUE TITLE
Requests version requirements?

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/confluent-docker-utils#1]
https://github.com/confluentinc/confluent-docker-utils/blob/master/requirements.txt#L4

This line has: requests!=2.11.0,<2.12,>=2.6.1

We usually have request 2.18 running and this requirement breaks our scripts out of the box. Things used to work in 3.3.1 with this.

Is there any reason to enforce stricter requirements on requests package? And not use the latest 2.18.4?

cf https://github.com/confluentinc/cp-docker-images/issues/386

**Comment by ewencp** [comment]
@aayars Any ideas here? Looks like you were previously updating to 2.13 but ended up reverting it.

**Comment by aayars** [comment]
It may have been due to the docker-compose API, IIRC. Could try bumping to latest to see what breaks!

**Comment by andrewegel** [comment]
We have since bumped the requests version and dropped python2.7 support.
