### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by frek818** [confluentinc/confluent-docker-utils#21]
Out of curiosity I was exploring the build system of kafka and stumbled upon a little bug in some python logic. https://github.com/confluentinc/confluent-docker-utils/pull/20

I don’t know how crucial it is to the project but I figure I should point it out. The jenkins build failed for some logistical reason.

I ran pytest for new test that was added and it passed. The Jenkins failure appear to be due to some administrative task. Im not sure. Can someone take a look?

**Comment by andrewegel** [comment]
Jenkins is building the project normally as of this moment.
