### ISSUE TITLE
check_connect_ready must wait for start rest service

### ISSUE THREAD

**Issue by falkolab** [confluentinc/confluent-docker-utils#25]
I'v got 404 error in my local docker environment when execute command
```
bash -c 'cub connect-ready {host} {port} 60 && echo PASS || echo FAIL'
```
Becouse wrong kafka ready state detection.

`check_connect_ready` command must wait for 20x status in loop several times with time.sleep(1) while 404 status code received from rest api during bootstrap initialisation.

**Comment by andrewegel** [comment]
If I'm understanding things here:

* Connect Process begins listening on a port, this check passes: https://github.com/confluentinc/confluent-docker-utils/blob/master/confluent/docker_utils/cub.py#L249
* But internally the connect process isn't ready and still initializing (?), and returns 404 and fails here: https://github.com/confluentinc/confluent-docker-utils/blob/master/confluent/docker_utils/cub.py#L256
* Later the connect process finishes initializing, and starts returning 200s, but by the time this happens, the cub script has failed, and bubbled that failure up to your orchestration system indicating a failure.
